### ISSUE TITLE
Bip39 Seed

### ISSUE THREAD

**Issue by Ketrab282** [Bithomp/bithomp-tools#4]
Hello,

Hello,

I have a question about adding additional security to Bithomp Tools Master.

I have 12 word mnemonic + 1 word BIP39 Seed.

In such a situation, when the account is secured with an additional word, I cannot use the Bithomp-Tools-Master tool.

**Comment by ihomp** [comment]
the tool can be updated to support the +1 word, but we dropped the support...
We might find time to approve a PR if you would like to contribute.

**Comment by Ketrab282** [comment]
Thank you for your answer.
I would love to contribute but I don't know the programming language.

It is a pity that the word +1 was dropped

Regards

**Comment by ihomp** [comment]
The word+1 was never supported in bithomp-tool, but that can be added to bithomp tools to support it.
We just do not work on that project any longer, someone else can send a PR so we could approve it.

**Comment by ihomp** [comment]
@Ketrab282 you've got powerful friends, @Wietse-Livingroom solved your request :) 
its merged to master

**Comment by ihomp** [comment]
@Ketrab282 we deployed a new version of tools to testnet 
https://test.bithomp.com/tools/

you can also just download the repo and try it locally 

let me know if it works for you, so we can close the issue :)

**Comment by Ketrab282** [comment]
Great.
Thank you very much for taking my question seriously.
Thank you for the great communication.

**Comment by Ketrab282** [comment]
Because I forgot to add.
I downloaded it to my computer and of course it works.
Thanks again and best regards.
