### ISSUE TITLE
Set an icon for a currency

### ISSUE THREAD

**Issue by Mwni** [Bithomp/bithomp-tools#5]
Is there a way to specify an icon for a specific trustline? I've seen this for Bitstamp USD and others. Setting a wallet Gravatar does not work.

**Comment by ihomp** [comment]
there is no way to do it with the bithomp-tools, if you write to our: support at bithomp dot com then we might add your icon and keep it locally to show to bithomp users. (It's good if you have the account already verified with xumm)

**Comment by Mwni** [comment]
Thank you
